### ISSUE TITLE
Suggestion: dump printable character with `--dumpkeys`

### ISSUE THREAD

**Issue by mgrojo** [SMerrony/keypadder#1]
**Describe the bug**
The # virtual key produced ç instead of #.

**To Reproduce**
1. Go to 'Hex'
2. Click on '#'

**Expected behavior**
I expected # to be input, but it produced ç.

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.1 LTS
- Browser Firefox
- Keyboard distribution: Spain

**Additional context**

Congratulations on this useful and simple tool.

I suppose this depends on keyboard distribution.

Edit: Before submitting this issue I read the documentation, and understand this is expected behaviour, so you can directly close it, but I've thought that a possible improvement is to dump the actual printable character (when applicable) when the `--dumpkeys` option is used. In that way, you could predict which character will be printed while configuring your pads.

**Comment by SMerrony** [comment]
Thanks for the suggestion, but now (thanks to you) we have many non-printable application control codes etc. in the list, I don't think we want splurge them all out ;-)  
I don't think we want to go down the route of adding metadata to the key codes.

**Comment by mgrojo** [comment]
I was thinking in some way to programmatically convert from the code to the character, but I've made a search and haven't found a way. Thus, I will close this issue. It's just a matter of reading the documentation and compare your layout to the US layout.

Maybe you can link in the documentation to something like this:
https://www.w3.org/TR/uievents-code/#key-alphanumeric-writing-system
