### ISSUE TITLE
Program raises CONSTRAINT_ERROR on invalid configuration (no port)

### ISSUE THREAD

**Issue by mgrojo** [SMerrony/keypadder#4]
**Describe the bug**
I made a new configuration file, but I forgot about the keypadder section. 

**To Reproduce**
1. Remove keypadder section in examples/keypadder.xml
3. Run normally
4. Program fails with CONSTRAINT_ERROR due to invalid data reading the port number

**Expected behavior**
Either a default value is used or the program aborts when reading the configuration file, stating that the section is mandatory.

**Additional context**
I fixed it using a default initialization, but you might prefer the other way.

```diff
diff --git a/src/config.ads b/src/config.ads
index 2c68b63..9d3212e 100644
--- a/src/config.ads
+++ b/src/config.ads
@@ -11,7 +11,7 @@ package Config is
 
    type Port_T is range 1 .. 65535;
    type Keypadder_Conf_T is record
-      Port : Port_T;
+      Port : Port_T := 8082;
    end record;
 
    type Up_Down_T is (Up, Down);
```

**Comment by SMerrony** [comment]
I'll address this at the same time as Issue #6, by adding a validation phase for the config.
