### ISSUE TITLE
Storage_Error when the file has more than 8 tabs

### ISSUE THREAD

**Issue by mgrojo** [SMerrony/keypadder#6]
**Describe the bug**
There's a Storage_Error when the file has more than 8 tabs or more than some other unknown limit.

**To Reproduce**

1. Unzip [math_conf.zip](https://github.com/SMerrony/keypadder/files/10716465/math_conf.zip) in keypadder root
2. Run `sudo bin/keypadder --verbose examples/math_no_ok.toml`
3. A Storage_Error is raised for an Unbounded_String object:
```
[...]
Key No.  9 is: &#x2119;
Key No.  10 is: &#x211A;
Key No.  11 is: &#x2124;
Error loading configuration file: examples/math.toml
raised PROGRAM_ERROR : adjust/finalize raised STORAGE_ERROR: s-intman.adb:136 explicit raise
[/home/mgr/src/github/SMerrony/keypadder/bin/../../../../..//.config/alire/cache/dependencies/gnat_native_12.2.1_11f3b811/lib/gcc/x86_64-pc-linux-gnu/12.2.0/adalib/libgnat-12.so]
0x7f4bec5b70b8 ada__strings__unbound
ed___assign__2.cold at ???
[bin/keypadder]
0x4394b2 Config.Load_Config_File at config.adb:121
0x421438 Keypadder at keypadder.adb:68
0x422edc Main at b__keypadder.adb:1331
[/lib/x86_64-linux-gnu/libc.so.6]
0x7f4bec14bd8e
0x7f4bec14be3e
[bin/keypadder]
0x420883 _start at ???
0xfffffffffffffffe
```
**Expected behavior**
Although the configuration file is big, I suppose it should be loaded, or at least, a message explaining that some limit has been surpassed.

I truncated the file (`examples/math.toml`) to have 8 tabs and it works.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - GNAT version: gnat_native_12.2.1_11f3b811
 
**Additional context**
It might be a problem in GNAT or in ada-toml?

**Comment by SMerrony** [comment]
This is just hitting a limit I put in the code (config.ads:50) to make sure the parser didn't go bananas.

I'm going to review the whole TOML-correctness/parsing area this week - so please hold off on these things for a couple of days :-)

**Comment by mgrojo** [comment]
My math example should work now. Would you like to add it? I can make a pull request, if you want.

**Comment by SMerrony** [comment]
Yes - please do.
